# Generated by Django 4.1.7 on 2023-03-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='in_stock',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
