# Generated by Django 4.1.7 on 2023-03-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_in_stock_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='on_sale',
            field=models.BooleanField(null=True),
        ),
    ]
