# Generated by Django 4.1.7 on 2023-03-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_on_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='on_sale',
        ),
        migrations.AddField(
            model_name='products',
            name='discount_percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
