# Generated by Django 4.1.7 on 2023-03-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productslikes_user_productscart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_percentage',
            field=models.FloatField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(default=1, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productscart',
            name='quantity',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
