# Generated by Django 4.1.7 on 2023-04-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_percentage',
            field=models.FloatField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.FloatField(default=1, max_length=100, null=True),
        ),
    ]
